"""Deterministic contract primitives for Vera Mesh."""

from .contracts import (
    CAPABILITIES_SCHEMA,
    DIAGNOSTIC_RECEIPT_SCHEMA,
    DIAGNOSTIC_STATUSES,
    HELLO_SCHEMA,
    PAIR_CONTRACT_SCHEMA,
    RUNTIME_PROFILE_SCHEMA,
    ComponentDigestEvidence,
    ContractValidationError,
    RuntimeProfileManifest,
    bind_runtime_profile,
    build_runtime_profile_manifest,
    runtime_profile_digest,
    validate_bound_message,
    validate_runtime_profile_manifest,
)
from .digests import (
    PACKET_DIGEST_VECTORS,
    PACKET_METADATA_EXCLUSIONS,
    DigestValidationError,
    DigestVector,
    PacketDigest,
    PacketDigestVector,
    build_digest_vector,
    canonical_json_bytes,
    packet_canonical_bytes,
    packet_digest,
    sha256_hex,
    validate_sha256,
)

__all__ = [
    "CAPABILITIES_SCHEMA",
    "ComponentDigestEvidence",
    "ContractValidationError",
    "DIAGNOSTIC_RECEIPT_SCHEMA",
    "DIAGNOSTIC_STATUSES",
    "DigestValidationError",
    "DigestVector",
    "HELLO_SCHEMA",
    "PACKET_DIGEST_VECTORS",
    "PACKET_METADATA_EXCLUSIONS",
    "PAIR_CONTRACT_SCHEMA",
    "PacketDigest",
    "PacketDigestVector",
    "RUNTIME_PROFILE_SCHEMA",
    "RuntimeProfileManifest",
    "bind_runtime_profile",
    "build_digest_vector",
    "build_runtime_profile_manifest",
    "canonical_json_bytes",
    "packet_canonical_bytes",
    "packet_digest",
    "runtime_profile_digest",
    "sha256_hex",
    "validate_bound_message",
    "validate_runtime_profile_manifest",
    "validate_sha256",
]
